---
apiVersion: v1
kind: Pod
metadata:
  name: empms-db
  labels:
    app: empms-db
spec:
  containers:
  - name: empms-db
    image: 390606000562.dkr.ecr.ap-south-1.amazonaws.com/mysql:latest
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "password"
    - name: MYSQL_DATABASE
      value: "attendancedb"

---
apiVersion: v1
kind: Pod
metadata:
  name: empms-es
  labels:
    app: empms-es
spec:
  containers:
  - name: empms-es
    image: 390606000562.dkr.ecr.ap-south-1.amazonaws.com/elasticsearch:latest
    ports:
    - containerPort: 9200
    env:
    - name: ES_JAVA_OPTS
      value: "-Xmx512m -Xms512m"
    - name: ELASTIC_PASSWORD
      value: "elastic"

---
apiVersion: v1
kind: Pod
metadata:
  name: empms-attendance
  labels:
    app: empms-attendance
spec:
  containers:
  - name: empms-attendance
    image: 390606000562.dkr.ecr.ap-south-1.amazonaws.com/attendance:latest
    ports:
    - containerPort: 8081

---
apiVersion: v1
kind: Pod
metadata:
  name: empms-salary
  labels:
    app: empms-salary
spec:
  containers:
  - name: empms-salary
    image: 390606000562.dkr.ecr.ap-south-1.amazonaws.com/salary:latest
    ports:
    - containerPort: 8082

---
apiVersion: v1
kind: Pod
metadata:
  name: empms-employee
  labels:
    app: empms-employee
spec:
  containers:
  - name: empms-employee
    image: 390606000562.dkr.ecr.ap-south-1.amazonaws.com/employee:latest
    ports:
    - containerPort: 8083

---
apiVersion: v1
kind: Pod
metadata:
  name: empms-frontend
  labels:
    app: empms-frontend
spec:
  containers:
  - name: empms-frontend
    image: 390606000562.dkr.ecr.ap-south-1.amazonaws.com/frontend:latest
    ports:
    - containerPort: 5000

---
apiVersion: v1
kind: Pod
metadata:
  name: empms-webserver
  labels:
    app: empms-webserver
spec:
  containers:
  - name: empms-webserver
    image: 390606000562.dkr.ecr.ap-south-1.amazonaws.com/webserver:latest
    ports:
    - containerPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: empms-gateway
  labels:
    app: empms-gateway
spec:
  containers:
  - name: empms-gateway
    image: 390606000562.dkr.ecr.ap-south-1.amazonaws.com/gateway:latest
    ports:
    - containerPort: 8080
