---
apiVersion: v1
kind: Service
metadata:
  name: empms-db
spec:
  selector:
    app: empms-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: empms-es
spec:
  selector:
    app: empms-es
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200

---
apiVersion: v1
kind: Service
metadata:
  name: empms-attendance
spec:
  selector:
    app: empms-attendance
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: empms-salary
spec:
  selector:
    app: empms-salary
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082

---
apiVersion: v1
kind: Service
metadata:
  name: empms-employee
spec:
  selector:
    app: empms-employee
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083

---
apiVersion: v1
kind: Service
metadata:
  name: empms-frontend
spec:
  selector:
    app: empms-frontend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: empms-webserver
spec:
  selector:
    app: empms-webserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: empms-gateway
spec:
  selector:
    app: empms-gateway
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
